### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by stasglazkov1995** [stasglazkov1995/homepage#6]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by AnnaVeronika-Volytska** [comment]
We are "Runner". And our company have specialized in robotic delivery. We love to make our lives more comfortable and learn robots to do works that are boring for people. This means less repetitive work and more time for innovation people will have. And we need to create a platform that will be secured and help people to post their packages.

**Comment by stasglazkov1995** [comment]
Thanks. Good job 👍

**Comment by AnnaVeronika-Volytska** [comment]
I am an ASP.NET developer. I hold a degree in Computer
Automation. I minored in Programming with a focus on ASP.NET tech.
My attention to detail, communication, and time management skills have proven beneficial to
various software and systems development projects.
