### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by stasglazkov1995** [stasglazkov1995/homepage#7]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by AnnaVeronika-Volytska** [comment]
# Useful Links
-  [https://www.getrunner.io/](https://www.getrunner.io/)

-  [https://runner.one/](https://runner.one/)

**Comment by AnnaVeronika-Volytska** [comment]
# Hlazkov Stanislav
-  [FaceBook](https://www.facebook.com/nazarkolmander)
-  [glazkov691](https://www.instagram.com/glazkov691/)
- [stasglazkov1995](https://github.com/stasglazkov1995)
