### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by stasglazkov1995** [stasglazkov1995/homepage#8]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by AnnaVeronika-Volytska** [comment]
### Runner timeline

 **2019**

- Delivery began in Irvine, California. Under the same operating conditions used in Snohomish, WA.

 **2020**

- Runner robots operated in Atlanta, Georgia, and Franklin, Tennessee as well.

 **2021**

- Trials are being conducted at locations like college campuses and office complexes. Delivery with Runner robots around the US also continued through the COVID-19 pandemic to minimize human-to-human contact.

**Comment by AnnaVeronika-Volytska** [comment]
### Timeline

 **2020**

- HTML5/CSS3/JavaScript(Course) During these courses I had the opportunity to get acquainted with the wonderful world of the front-end

**2020**

- Made the decision to become a developer. I decided that my future job would be to help people get rid of routine work and spend more time expressing their creativity.

 **2016**

- Ternopil Smart City Hackathon. Where I with my team propose to the city decide problem with traffic, and detect people which travel without a ticket.

**2015**
- Trip around Ukraine. With my friends, we visit many towns in Ukraine such as Uzhgorod, Cherkasy, Kyiv, Lviv, Ternopil, Chernivtsi.
