### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by stasglazkov1995** [stasglazkov1995/homepage#9]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by AnnaVeronika-Volytska** [comment]
[Runner](https://media2.s-nbcnews.com/j/newscms/2018_49/2602896/181012-robot-boston-dynamics-2x1-mn-1630_d1412bb423d9e943d0e013d656061b52.fit-760w.gif) -Runner is a 6 wheeled robot used to deliver packages for the E-commerce site, Amazon.com. Runner  originally debuted on January 23, 2019, delivering packages to Amazon customers in Snohomish County, Washington. Runner  move on sidewalks, at a walking pace. In August, 2019, the robots started delivering packages to customers Irvine, California on a test basis, with human monitors. The package is stored inside of the robot, and driven to the customer.

Runner acquired the robotics company Dispatch to build the robot.

**Comment by AnnaVeronika-Volytska** [comment]
SKILLS
COMMUNICATION, ANALYTICAL AND RESEARCH, ADAPTABILITY, FLEXIBILITY, TEAM WORKER,  DECISION-MAKING, PROBLEM-SOLVING, EASY-GOING, PLANNING, GOOD SENSE OF HUMOUR, TO DO-LIST MAKING, TIME-MANAGEMENT, ATTENTION TO DETAIL, SELF-CONFIDENCE, CREATIVITY, STRONG WORK ETHIC, SUPPORT,  LEARNING FROM CRITICISM, MATHEMATICS

LANGUAGES
UKRAINIAN RUSSIAN ENGLISH POLISH

CHARACTER
ADVENTUROUS, AMBITIOUS, TALKATIVE, RELAXED, PUNCTUAL, PATIENT, INTUITIVE, HONEST, ENERGETIC, CURIOSITY, CREATIVE, OPEN-MINDED, CHEERFUL, FOCUSED, MOTIVATED, HARD-WORKING

LIKES
CHESS, BICYCLE, TRAVELING, POLITICS, STARTUPS, COOKING, SPORTS, DISCUSSION, YOGA, HISTORY, WALKING, CAMPING, HIKING, COFFEE, PROGRAMMING, CYBERPUNK, GAMES OF THRONES, STREET FOOD, CANOES, MOUNTAINS, MEMES

DISLIKES
PANIC, HOME-SITTING, BEING ALONE, FREE-ALCOHOL BEER, RAISINS, FAKE EYEBROWS, INDIAN FOOD, WAR, SUIT, TIE, DRAMA, ACTING STUPID, DUCK FACE SELFIES

WANTS
A GOOD HAIRCUT, MONEY, SELF-DEVELOPMENT, INTERESTING JOB, STAY IN GOOD SHAPE, TRAVEL TRAILER, BIG HOUSE, REMOVAL WORK, SURFING LESSONS
